language: python
python:
    - "2.7"
sudo: false
cache:
    directories:
        - "~/.platformio"

install:
    - pip install -U platformio
    - platformio update

script:
  # Install EasyNTPClient (Library ID 1734)
    - platformio lib -g install 1734
    - platformio run